trigger:
- idt-feature-*

pool:
  vmImage: ubuntu-latest
  
steps:
  - task: TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: 0.13.0
  
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'CSL Staging'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az --version
        az account show
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd environments/master
        ../../scripts/ci/validate_envs.sh
  