trigger:
- idt-feature-*

pool:
  vmImage: ubuntu-latest
  
steps:

  - task: CmdLine@2
    displayName: Validate environments
    inputs:
      script: 'az account list'

  # - task: TerraformInstaller@0
  #   displayName: Install Terraform
  #   inputs:
  #     terraformVersion: 0.13.0
      
  # - task: CmdLine@2
  #   displayName: Validate environments
  #   inputs:
  #     script: './scripts/ci/validate_envs.sh'
