trigger:
- idt-feature-*

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: latest
      
  - task: CmdLine@2
    displayName: Validate environments
    inputs:
      script: './scripts/ci/validate_envs.sh'
