module "postgres" {
  source                   = "../../modules/postgres"
  rg_name                  = "${var.rg_name}"
  rg_prefix                = "${var.rg_name}"
  rg_location              = "${var.rg_location}"
  postgres_name            = "${var.rg_name}-${var.postgres_name}"
  postgres_sku_name        = "${var.postgres_sku_name}"
  postgres_sku_capacity    = "${var.postgres_sku_capacity}"
  postgres_sku_tier        = "${var.postgres_sku_tier}"
  postgres_admin_login     = "${var.postgres_user}"
  postgres_admin_pass      = "${var.postgres_pass}"
  postgres_version         = "9.6"
  postgres_storage_mb      = "51200"
  postgres_ssl_enforcement = "Enabled"
  env_profile              = "${var.env_profile}"
}

module "wso2" {
  source                = "../../modules/wso2"
  rg_name               = "${var.rg_name}"
  rg_prefix             = "${var.rg_prefix}"
  rg_location           = "${var.rg_location}"
  wso2_name             = "${var.rg_name}-${var.wso2_name}"
  database_url          = "jdbc:postgresql://${var.rg_name}-${var.postgres_name}.postgres.database.azure.com:5432/wso2is?user=${var.postgres_user}@${var.rg_name}-${var.postgres_name}&password=${var.postgres_pass}&ssl=true"
  docker_image          = "${var.wso2_docker_image}"
  docker_tag            = "${var.wso2_docker_tag}"
  hammer_logstash_host  = "${var.hammer_logstash_host}"
  hammer_logstash_port  = "${var.hammer_logstash_port}"
  env_profile           = "${var.env_profile}"
  lpg_ui_url            = "${var.lpg_ui_url}"
  lpg_management_ui_url = "${var.lpg_management_ui_url}"
}
